services:
  - type: web
    name: inventory-and-sales-tracker
    runtime: dotnet
    runtimeVersion: 8.0.12
    buildCommand: dotnet publish -c Release -o ./out
    startCommand: cd ./out && dotnet Inventory_and_Sales_Tracker.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:${PORT}
    disk:
      name: inventory-db
      mountPath: /data
      sizeGB: 1
